# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-default-conf
#   namespace: nginx-proxy-manager
# data:
#   default.conf: |
#     # Conteúdo do seu arquivo default.conf aqui
#     server {
#         listen 443 ssl;
#         server_name _;

#         ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
#         ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

#         location / {
#             proxy_pass http://localhost:3000;
#         }
#     }
#     server {
#       listen 443 ssl;
#       server_name 192.168.68.136;  # O IP do seu servidor

#       ssl_certificate /etc/nginx/ssl/nginx.crt;
#       ssl_certificate_key /etc/nginx/ssl/nginx.key;

#       # Configurações adicionais de SSL
#       ssl_protocols TLSv1.2 TLSv1.3;
#       ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256';
#       ssl_prefer_server_ciphers on;

#       # Configurações adicionais do servidor
#       location / {
#           proxy_pass http://localhost:80;
#           proxy_set_header Host $host;
#           proxy_set_header X-Real-IP $remote_addr;
#           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header X-Forwarded-Proto $scheme;
#       }
#   }

#   server {
#       listen 80;
#       server_name 192.168.68.136;

#       location / {
#           return 301 https://$host$request_uri;
#       }
#   }

