apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.nginxProxyManager.persistence.size }}
  accessModes:
    - {{ .Values.nginxProxyManager.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data/{{ .Release.Name }}
