apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.nginxProxyManager.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.nginxProxyManager.service.ports.http }}
      targetPort: {{ .Values.nginxProxyManager.service.ports.http }}
    - name: https
      port: {{ .Values.nginxProxyManager.service.ports.https }}
      targetPort: {{ .Values.nginxProxyManager.service.ports.https }}
    - name: management
      port: {{ .Values.nginxProxyManager.service.ports.management }}
      targetPort: {{ .Values.nginxProxyManager.service.ports.management }}
      nodePort: {{ .Values.nginxProxyManager.service.ports.managementNodePort }}