apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.nginxProxyManager.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nginxProxyManager.service.ports.http }}
    - name: https
      port: 443
      targetPort: 443
      nodePort: {{ .Values.nginxProxyManager.service.ports.https }}
    - name: management
      port: 81
      targetPort: 81
      nodePort: {{ .Values.nginxProxyManager.service.ports.management }}