{{- if .Values.nginxProxyManager.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /etc/letsencrypt
{{- end }}
