{{- if .Values.nginxProxyManager.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
