{{- if .Values.nginxProxyManager.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.nginxProxyManager.persistence.size }}
  accessModes:
    - {{ .Values.nginxProxyManager.persistence.accessMode }}
  hostPath:
    path: /etc/letsencrypt
{{- end }}
