{{- if .Values.nginxProxyManager.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.nginxProxyManager.persistence.size }}
  accessModes:
    - {{ .Values.nginxProxyManager.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data/nginx-proxy-manager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-proxy-manager-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.nginxProxyManager.persistence.size }}
  accessModes:
    - {{ .Values.nginxProxyManager.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data/nginx-proxy-manager
{{- end }}
