replicaCount: 1

image:
  repository: lscr.io/linuxserver/speedtest-tracker
  tag: "0.20.6"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30002
  httpsPort: 443
  httpsNodePort: 30003

ingress:
  enabled: true
  name: ""
  className: "nginx"
  path: /
  hosts:
    - host: speed-tracker.tmaia.cloud
      paths:
        - /
  tls: []

resources: {}
  
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  className: manual

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: APP_URL
    value: "https://speed-tracker.tmaia.cloud"
  - name: APP_KEY
    value: "base64:GLVLJVzzYOqek3q6n7js99hcoQDDfLBR0gsOWdnmkFE="
  - name: DB_CONNECTION
    value: "sqlite"
  - name: SPEEDTEST_SCHEDULE
    value: "0 * * * *"
  - name: SPEEDTEST_SERVERS
    value: ""
  - name: PRUNE_RESULTS_OLDER_THAN
    value: ""
  - name: CHART_DATETIME_FORMAT
    value: ""
  - name: DATETIME_FORMAT
    value: ""
  - name: APP_TIMEZONE
    value: "America/Fortaleza"
  - name: DISPLAY_TIMEZONE
    value: "America/Fortaleza"
  - name: DASHBOARD_POLLING
    value: "10s"
  - name: RESULTS_POLLING
    value: "10s"
  - name: AUTH
    value: "false"
  - name: PUBLIC_DASHBOARD
    value: "true"
