replicaCount: 1

image:
  repository: lscr.io/linuxserver/speedtest-tracker
  tag: "0.20.6"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30002
  httpsPort: 443
  httpsNodePort: 30003

cloudflare:
  # Your Cloudflare account number.
  account: ""
  # The name of the tunnel this instance will serve
  tunnelName: ""
  # The ID of the above tunnel.
  tunnelId: ""
  # The secret for the tunnel.
  secret: ""
  # If defined, no secret is created for the credentials, and instead, the secret referenced is used
  secretName: null
  # If true, turn on WARP routing for TCP
  enableWarp: false
  # Define ingress rules for the tunnel. See
  # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
  ingress: []
    # The first rule proxies traffic to the httpbin sample service named web-server at port 80
    # - hostname: tunnel.example.com
    #  service: http://web-service:80
    # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
    # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
    # in the connection from cloudflared to your local service, not from the internet to cloudflared.
    # - hostname: hello.example.com
    #   service: hello_world

ingress:
  enabled: true
  name: ""
  className: "nginx"
  path: /
  hosts:
    - host: speed-tracker.tmaia.cloud
      paths:
        - /
  tls: []

resources: {}
  
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  className: manual

# volumes:
#   - name: speedtest-tracker-config
#     persistentVolumeClaim:
#       claimName: speedtest-tracker-pvc

# volumeMounts:
#   - name: speedtest-tracker-volumeMount
#     mountPath: /mnt/data/speedtest-tracker

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: APP_URL
    value: "https://speed-tracker.tmaia.cloud"
  - name: APP_KEY
    value: "base64:GLVLJVzzYOqek3q6n7js99hcoQDDfLBR0gsOWdnmkFE="
  - name: DB_CONNECTION
    value: "sqlite"
  - name: SPEEDTEST_SCHEDULE
    value: "0 * * * *"
  - name: SPEEDTEST_SERVERS
    value: ""
  - name: PRUNE_RESULTS_OLDER_THAN
    value: ""
  - name: CHART_DATETIME_FORMAT
    value: ""
  - name: DATETIME_FORMAT
    value: ""
  - name: APP_TIMEZONE
    value: "America/Fortaleza"
  - name: DISPLAY_TIMEZONE
    value: "America/Fortaleza"
  - name: DASHBOARD_POLLING
    value: "10s"
  - name: RESULTS_POLLING
    value: "10s"
  - name: AUTH
    value: "false"
  - name: PUBLIC_DASHBOARD
    value: "true"
