apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librespeed-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: speed-internal.tmaia.cloud  # Substitua por seu domínio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "librespeed.name" . }}
            port:
              number: 80
