apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 85
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default 30000 }}
  selector:
    app: {{ .Release.Name }}
