# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 85
      nodePort: 80
  selector:
    app: {{ .Release.Name }}
