replicaCount: 1

image:
  nextcloud: nextcloud
  mariadb: mariadb:10.6

service:
  app:
    type: NodePort
    port: 80
    nodePort: 30015
  db:
    type: NodePort
    port: 3306
    nodePort: 30014

persistence:
  smb:
    username: nextcloud
    password: nextcloud
    volumeHandle: //<your-smb-server-ip>/<Folder-shared>
    source: //<your-smb-server-ip>/<Folder-shared>
  app:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: local-storage
  db:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: local-storage

nextcloud:
  adminUser: admin
  adminPassword: admin
  dataDir: /var/www/html/data

mariadb:
  image:
    repository: mariadb
    tag: 10.6
    pullPolicy: IfNotPresent
  rootPassword: "nextcloud"
  database: nextcloud
  user: nextcloud
  password: "nextcloud"
  host: 172.16.249.94

ingress:
  enabled: false
