replicaCount: 1

image:
  nextcloud: nextcloud

service:
  app:
    type: NodePort
    port: 80
    nodePort: 30015
  db:
    type: NodePort
    port: 3306
    nodePort: 30014

persistence:
  smb:
    username: nextcloud
    password: nextcloud
    volumeHandle: //<your-smb-server-ip>/<Folder-shared>
    source: //<your-smb-server-ip>/<Folder-shared>
    storageClassName: nextcloud-smb-storage-class
    dirMode: dir_mode=0770
    fileMode: file_mode=0770
  app:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: local-storage
  data:
    enabled: true
    size: 50Gi
    accessMode: ReadWriteOnce
    storageClassName: nextcloud-smb-storage-class
  db:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: nextcloud-smb-storage-class

nextcloud:
  adminUser: admin
  adminPassword: admin
  dataDir: /mnt/data/nextcloud-data

mariadb:
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  rootPassword: "nextcloud"
  database: nextcloud
  user: nextcloud
  password: "nextcloud"
  host: nextcloud-db.nextcloud.svc.cluster.local

ingress:
  enabled: false
