replicaCount: 1

image:
  nextcloud: nextcloud
  mariadb: mariadb:10.6

service:
  app:
    type: NodePort
    port: 80
    nodePort: 30013
  db:
    type: NodePort
    port: 3306
    nodePort: 30012

persistence:
  smb:
    username:
    password:
    volumeHandle:
    source: 
  app:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: local-storage
  db:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: local-storage

nextcloud:
  adminUser: admin
  adminPassword: admin
  dataDir: /var/www/html/data

mariadb:
  rootPassword: ""
  database: nextcloud
  user: nextcloud
  password: ""

ingress:
  enabled: false
