apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
      nodePort: {{ .Values.service.httpsNodePort }}
  selector:
    app: {{ .Release.Name }}
