apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: librespeed
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: librespeed
