apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.nextcloud }}
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.user }}
            - name: MYSQL_HOST
              value: {{ .Values.mariadb.host }}
            - name: MYSQL_PORT_NUMBER
              value: "3306"
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: NEXTCLOUD_ADMIN_USER
              value: {{ .Values.nextcloud.adminUser }}
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: {{ .Release.Name }}-admin-password
            - name: NEXTCLOUD_DATA_DIR
              value: {{ .Values.nextcloud.dataDir }}
            - name: NEXTCLOUD_TRUSTED_DOMAINS 
              value: {{ .Values.nextcloud.trustedDomains }}
          volumeMounts:
            - name: {{ .Release.Name }}-app
              mountPath: /var/www/html
            - name: {{ .Release.Name }}-data
              mountPath: {{ .Values.nextcloud.dataDir }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo \"ServerName documentos.tmaia.cloud\" | tee -a /etc/apache2/apache2.conf"]
      volumes:
        - name: {{ .Release.Name }}-app
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-pvc
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Namespace }}-db
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: {{ .Release.Name }}-db
          image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: {{ .Release.Name }}-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: {{ .Release.Name }}-db-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-db-pvc
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     run: haproxy-ingress
#   name: {{ .Release.Name }}-collaborative
#   namespace: {{ .Release.Name }}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       run: haproxy-ingress
#   template:
#     metadata:
#       labels:
#         run: haproxy-ingress
#     spec:
#       serviceAccountName: {{ .Release.Name }}-collaborative
#       containers:
#       - name: haproxy-ingress
#         image: haproxytech/kubernetes-ingress
#         args:
#           - --configmap={{ .Release.Name }}/{{ .Release.Name }}-collaborative
#         securityContext:
#           runAsNonRoot: true
#           allowPrivilegeEscalation: false
#           runAsUser:  1000
#           runAsGroup: 1000
#           capabilities:
#             drop:
#               - ALL
#             add:
#               - NET_BIND_SERVICE
#           seccompProfile:
#             type: RuntimeDefault
#         resources:
#           limits:
#             memory: 2560Mi
#           requests:
#             memory: 2048Mi
#         livenessProbe:
#           httpGet:
#             path: /healthz
#             port: 1042
#         ports:
#         - name: http
#           containerPort: 8080
#         - name: https
#           containerPort: 8443
#         - name: stat
#           containerPort: 1024
#         env:
#         - name: TZ
#           value: "Etc/UTC"
#         - name: POD_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.name
#         - name: POD_NAMESPACE
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.namespace
