apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: {{ .Values.image.nextcloud }}
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.user }}
            - name: MYSQL_HOST
              value: db
            - name: NEXTCLOUD_ADMIN_USER
              value: {{ .Values.nextcloud.adminUser }}
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: nextcloud-admin-password
            - name: NEXTCLOUD_DATA_DIR
              value: {{ .Values.nextcloud.dataDir }}
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
