apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-app-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.app.size }}
  accessModes:
    - {{ .Values.persistence.app.accessMode }}
  storageClassName: {{ .Values.persistence.app.storageClassName }}
  hostPath:
    path: /mnt/data/{{ .Release.Name }}-app
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.data.size }}
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
   storageClassName: {{ .Values.persistence.data.className }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - {{ .Values.persistence.dirMode }}
    - {{ .Values.persistence.fileMode }}
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: {{ .Values.persistence.smb.volumeHandle }}/{{ .Release.Name }}/data  # Nome único do volume
    readOnly: false
    volumeAttributes:
      source: {{ .Values.persistence.smb.source }}/{{ .Release.Name }}/data  # Caminho SMB no TrueNAS
    nodeStageSecretRef:
      name: {{ .Release.Name }}-smb-secret
      namespace: {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.db.size }}
  accessModes:
    - {{ .Values.persistence.db.accessMode }}
  storageClassName: {{ .Values.persistence.db.storageClassName }}
  hostPath:
    path: /mnt/data/{{ .Release.Name }}-db
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
# spec:
#   capacity:
#     storage: {{ .Values.persistence.db.size }}
#   accessModes:
#     - {{ .Values.persistence.db.accessMode }}
#    storageClassName: {{ .Values.persistence.db.className }}
#   persistentVolumeReclaimPolicy: Retain
#   mountOptions:
#     - {{ .Values.persistence.db.dirMode }}
#     - {{ .Values.persistence.db.fileMode }}
#     - uid=1001
#     - gid=1001
#     - noperm
#     - mfsymlinks
#     - cache=strict
#     - noserverino  # required to prevent data corruption
#   csi:
#     driver: smb.csi.k8s.io
#     volumeHandle: {{ .Values.persistence.smb.volumeHandle }}/{{ .Release.Name }}  # Nome único do volume
#     readOnly: false
#     volumeAttributes:
#       source: {{ .Values.persistence.smb.source }}/{{ .Release.Name }}  # Caminho SMB no TrueNAS
#     nodeStageSecretRef:
#       name: {{ .Release.Name }}-smb-secret
#       namespace: {{ .Release.Name }}