apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.mariadb.rootPassword | b64enc }}
  mysql-password: {{ .Values.mariadb.password | b64enc }}
  nextcloud-admin-password: {{ .Values.nextcloud.adminPassword | b64enc }}
