apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smb-secret
  namespace: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.persistence.smb.username | b64enc }}
  password: {{ .Values.persistence.smb.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.mariadb.rootPassword | b64enc }}
  mysql-password: {{ .Values.mariadb.password | b64enc }}
  nextcloud-admin-password: {{ .Values.nextcloud.adminPassword | b64enc }}
