apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: 80
      nodePort: {{ .Values.service.app.nodePort }}
  selector:
    app: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: 3306
      nodePort: {{ .Values.service.db.nodePort }}
  selector:
    app: mariadb
