apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: 80
  selector:
    app: nextcloud
