apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.controller.argocdNamespace }}
spec:
  project: {{ .Values.controller.project }}
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: {{ .Values.controller.version }}
    path: argocd/ingress-nginx
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
