controller:
  replicaCount: 2
  service:
    type: LoadBalancer
  ingressClassResource:
    default: true

nginxProxyManager:
  enabled: true
  replicaCount: 1
  image: "jc21/nginx-proxy-manager:latest"
  service:
    type: NodePort
    ports:
      http: "80"
      https: "443"
      management: "81"
      management-nodePort: "30006"
  persistence:
    accessMode: ReadWriteOnce
    size: 1Gi
    className: manual
