{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Namespace }}
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}
    spec:
      containers:
        - name: {{ .Release.Namespace }}
          image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "externaldb" }}
                  key: db-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "externaldb" }}
                  key: db-password
                  key: db-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /var/lib/mysql
            # - name: owncloud-data
            #   mountPath: /mnt/owncloud-data
            #   readOnly: false
            # - name: owncloud-root-data
            #   mountPath: /mnt/data
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        # - name: owncloud-data
        #   persistentVolumeClaim:
        #     claimName: {{ .Release.Name }}-pvc
        # - name: owncloud-root-data
        #   persistentVolumeClaim:
        #     claimName: {{ .Release.Name }}-root-pvc
{{- end }}
