
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.smb.size }}
  accessModes:
    - {{ .Values.persistence.smb.accessMode }}
  storageClassName: {{ .Values.persistence.smb.className }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - {{ .Values.persistence.smb.dirMode }}
    - {{ .Values.persistence.smb.fileMode }}
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: {{ .Values.persistence.smb.volumeHandle }}  # Nome único do volume
    readOnly: false
    volumeAttributes:
      source: {{ .Values.persistence.smb.path }}  # Caminho SMB no TrueNAS
    nodeStageSecretRef:
      name: {{ .Release.Name }}-smb-secret
      namespace: {{ .Release.Name }}
{{- end }}
