
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.smb.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.smb.size }}
  volumeName: {{ .Release.Name }}-pv
  storageClassName: {{ .Values.persistence.smb.className }}
{{- end }}
