
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smb-secret
  namespace: {{ .Release.Name }}
  #namespace: default  # Modifique para o namespace correto
type: Opaque
data:
  username: {{ .Values.persistence.smb.username | b64enc }}
  password: {{ .Values.persistence.smb.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}