{{- if .Values.mariadb.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.smb.className }}
  namespace: {{ .Release.Name }}
provisioner: smb.csi.k8s.io
parameters:
  source: {{ .Values.smb.path }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .Release.Name }}-smb-secret 
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Name }} 
  csi.storage.k8s.io/node-stage-secret-name: {{ .Release.Name }}-smb-secret 
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Name }} 
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - sec=krb5
  - cruid=1000
  - seal
  - vers=3.0
  - nosuid
  - noexec
  - {{ .Values.persistence.smb.dirMode }}
  - {{ .Values.persistence.smb.fileMode }}
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino  # required to prevent data corruption
{{- end }}
