apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.owncloud.size }}
  accessModes:
    - {{ .Values.persistence.owncloud.accessMode }}
  # storageClassName: {{ .Values.persistence.owncloud.className }}
  persistentVolumeReclaimPolicy: Retain
  # mountOptions:
  #   - dir_mode=0777
  #   - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: {{ .Release.Name }}-pv  # Nome único do volume
    readOnly: false
    volumeAttributes:
      source: {{ .Values.smb.path }}  # Caminho SMB no TrueNAS
    nodeStageSecretRef:
      name: {{ .Release.Name }}-smb-secret
      namespace: {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-root-pv
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.owncloud.size }}
  accessModes:
    - {{ .Values.persistence.owncloud.accessMode }}
  storageClassName: {{ .Values.persistence.owncloud.className }}
  hostPath:
    path: /mnt/data/{{ .Release.Name }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain