{{- if .Values.persistence.owncloud.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    server: {{ .Values.persistence.owncloud.nfs.server }}
    path: {{ .Values.persistence.owncloud.nfs.path }}
{{end}}
---
{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.owncloud.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.owncloud.size }}
  volumeName: {{ .Release.Name }}-pv
  # storageClassName: {{ .Values.persistence.owncloud.className }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-root-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.owncloud.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.owncloud.size }}
  volumeName: {{ .Release.Name }}-root-pv
  storageClassName: {{ .Values.persistence.owncloud.className }}
{{- end -}}