apiVersion: v1
kind: Service
metadata:
  name: {{ include "owncloud.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: owncloud
      nodePort: {{ .Values.service.nodePort}}
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
      nodePort: {{ .Values.service.dbNodePort}}
  selector:
    {{- include "owncloud.selectorLabels" . | nindent 4 }}
{{- if not .Values.mariadb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "owncloud.fullname" . }}-db
  namespace: {{ .Release.Name }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
      nodePort: {{ .Values.service.dbNodePort}}
  selector:
    app: {{ .Release.Namespace }}-db
{{- end }}
