apiVersion: v1
kind: Service
metadata:
  name: {{ include "owncloud.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort}}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.dbNodePort}}
  selector:
    {{- include "owncloud.selectorLabels" . | nindent 4 }}