nginxProxyManager:
  replicaCount: 3
  image: "jc21/nginx-proxy-manager:latest"
  service:
    type: NodePort
    ports:
      http: "80"
      https: "443"
      management: "81"
      managementNodePort: "30006"
  persistence:
    accessMode: ReadWriteOnce
    size: 1Gi
    className: manual
