nginxProxyManager:
  replicaCount: 3
  image: "jc21/nginx-proxy-manager:latest"
  SSL_ACTIVE: "true"
  service:
    type: NodePort
    ports:
      http: "30007"
      https: "30008"
      management: "30006"
  persistence:
    accessMode: ReadWriteMany
    size: 1Gi
    className: manual
