apiVersion: v1
kind: Pod
metadata:
  name: pv-cleaner
  namespace: portainer
spec:
  containers:
  - name: cleaner
    image: busybox
    command: ['sh', '-c', 'sleep 3600']  # Mantém o pod ativo por 1 hora
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: portainer-pvc
